apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: back-ingress
  labels:
    tier: backend
    name: back-ingress
spec:
  rules:
  - host: <Host>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <Service>
            port: 
              number: <Port>
