apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-sc
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: pd-standard
  replication-type: none # 단일 zone에서 사용